// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // Generated by `bun run auth:generate`; the CLI owns its formatting and any
    // fix applied here is lost on the next regeneration.
    ignores: ['server/db/schema.ts']
  }
  // Your custom configs here
)
